export type PageCompanionConfig = {
  name: string
  image: string
  alt: string

  title?: string
  messages: string[]

  exitTitle?: string
  exitMessage: string
  exitMark?: string

  side: 'left' | 'right'
  height: number
  offsetX: number

  bubbleOffsetX: number
  bubbleOffsetY: number
  bubbleWidth: number
  bubbleTailOffset: number

  exitMarkX: number
  exitMarkY: number
  exitMarkSize: number

  autoCycle?: boolean
  cycleInterval?: number
  doubleClose?: boolean
}


export const PAGE_COMPANIONS = {
  lion: {
    name: 'Lion_shipcrasher · 狮王',
    image: '/images/characters/lion-shipcrasher.png',
    alt: 'Lion_shipcrasher 狮王',
    side: 'left',
    height: 430,
    offsetX: 24,
    bubbleOffsetX: 48,
    bubbleOffsetY: 110,
    exitMark: '💢',
    exitMarkX: 42,
    exitMarkY: 9,
    exitMarkSize: 48,
    bubbleWidth: 320,
    bubbleTailOffset: 40,
    title: '狮王の贴心提示',
    messages: [
      '活动开始前记得先绑好复活点。至于飞船……最好别坐我的。',
      '重要装备别全带身上坐我的船，你永远不知道下一秒会发生什么。',
      '上船以后记得找位置坐好，星际公民的物理系统可不认识自己人。',
      '飞船起飞前最好确认所有人都上来了，我以前也是这么想的。',
      '下船之前先看看外面有没有地面，这个习惯真的很重要。',
      '看到我坐进驾驶位的时候，你还有最后一次下船的机会。',
      '请系好安全带。本次航班不保证抵达目的地。',
      '别担心，我这次真的会看高度表。哎，船怎么没电了。',
      '坠机状态已开启，板载!!!',
      '放心吧，这次活动我肯定不会坠机~',
      '酒馆里只能有一个亡牌驾驶员，那就是...',
    ],
    exitTitle: '狮王の最后警告',
    exitMessage: '我还会回来的！',
  },

  lucio: {
  name: 'LucioKop · Lucio',
  image: '/images/characters/luciokop.png',
  alt: 'LucioKop Lucio',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  exitMark: '💧',
  exitMarkX: 42,
  exitMarkY: 9,
  exitMarkSize: 42,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: 'LucioKopの温馨提示',
  messages: [
    '参加活动前记得先绑好附近的复活点，出事以后能少跑很多路。',
    '大型活动最好提前一小时上线，临开场才更新游戏就很尴尬了。',
    '需要共享屏幕的话记得提前测试一下，别等活动开始了才发现没画面。',
    '多人行动的时候尽量待在语音里，掉队了至少还能喊一声。',
    '今天什么活动？算我一个。',
    '人够了吗？不够我来。',
    '这种活动当然得来凑个热闹。',
    '活动结束别急着散啊，再聊会。',
  ],
  exitTitle: 'Lucio',
  exitMessage: '行，那我先撤，下次活动再喊我。',
},

inorath: {
  name: 'Inorath',
  image: '/images/characters/inorath.png',
  alt: 'Inorath',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: '逐星之翼 · 小提示',
  messages: [
    '速度不是一切，稳定地把每一个弯跑好才是关键。',
    '最快圈往往不是最激进的那一圈。',
    '先熟悉赛道，再去追那零点几秒。',
    '跑竞速别一上来就追求极限圈速，先把整条赛道稳定跑完通常更重要。',
    '第一次跑一张赛道先记检查点和下一个弯的位置，路线熟悉以后速度自然会上来。',
    '再来一圈，刚才至少还能快半秒。',
    '过弯不是越晚刹车越快，出弯速度有时候比入弯多抢那一点速度更重要。',
    '别看我撞了，线路是对的。',
    '连续弯提前想好下一两个弯怎么接，只盯着眼前的门很容易把后面的线路跑死。',
    '同一条赛道多跑几圈以后，可以开始找固定的刹车点和转向参照物。',
    '最后一圈。真的最后一圈。',
    '看别人快圈的时候别只看最高速度，注意他什么时候收油、什么时候开始转向更有用。',
    '想稳定提升圈速，一次只改一个地方。每个弯都换一种跑法，最后自己都不知道哪里变快了。',
    '比赛前最好先跑几圈把手感热起来，第一圈直接当排位圈通常不会是最快的。',
    '这圈不算，刚才那个弯没处理好。',
  ],
  exitTitle: 'Inorath',
  exitMessage: '那就终点见。',
  exitMark: '✨',
  exitMarkX: 42,
  exitMarkY: 9,
  exitMarkSize: 42,
},

ilqwqli: {
  name: 'ilQwQli',
  image: '/images/characters/ilqwqli.png',
  alt: 'ilQwQli',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: '绝境枪王 · 小提示',
  messages: [
    '枪法可以练，马枪也可以练。',
    '打 FPS 别一直把准星贴着地面走，提前保持在敌人可能出现的胸口高度，见面会快很多。',
    '别急，我听到他脚步了。',
    '换弹之前先找掩体，站在路中间换弹属于给对面提供温馨提示。',
    '进门之前先想好准星要看哪里，进门以后再找人通常已经慢了一步。',
    '你可以蹲那个角，但最好别让我知道你在那。',
    '听到脚步以后别急着乱跑，先判断方向和距离，有时候信息比先开枪更重要。',
    '别急着冲，先想想他下一秒会从哪里出来。',
    '倒地以后先报敌人的位置和方向，队友知道是谁打的你，比单纯喊“救我”有用。',
    '看到人再瞄已经晚了。',
    '近距离交火别只顾着开镜，有些武器直接腰射反而更容易处理突然贴脸的敌人。',
    '先活下来，再想怎么把对面全杀了。',
    '打一半血量不健康就先找机会治疗，带着残血继续找下一架通常活不到下一架。',
    '多人枪战尽量别和队友挤同一个门，两个人一起卡门口最后可能一个都进不去。',
    '清房间的时候别只看正前方，门后、角落和高低差位置都可能藏人。',
    '对枪打不过的时候先别急着怪武器，掩体、预瞄和先手往往比那一点面板差距更重要。',
    '地面 PVP 里知道什么时候不开枪也很重要，提前暴露位置可能比少打一个人更亏。',
    '咕咕嘎嘎。',
  ],
  exitTitle: 'ilQwQli',
  exitMessage: '行，下次枪王赛见。',
  exitMark: '...',
  exitMarkX: 42,
  exitMarkY: 9,
  exitMarkSize: 42,
},

asrcwww: {
  name: 'ASRC_WWW · 维克洛肝帝',
  image: '/images/characters/asrc-www.png',
  alt: 'ASRC_WWW 维克洛肝帝',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: '维克洛肝帝の攻略提示',
  messages: [
    '概率低不是问题，次数够多以后概率会向肝帝低头。',
    '想肝维克洛之前先看清楚兑换要求，最痛苦的不是肝，是肝完发现自己刷错材料了。',
    '维克洛的兑换任务要在 Emporium 里面接，看到想换的东西先去店里看对应的牌子和要求。',
    '维克洛任务要求的物资需要通过店里的货运电梯提交，带到空间站不等于已经交任务。',
    '维克洛的奖励不只有飞船，也有武器、护甲和舰船部件，进店以后别只盯着最大的那艘船。',
    '维克洛兑换获得的奖励会进入你交任务那个 Emporium 地点的本地库存，换完找不到东西先去那里看。',
    '维克洛现在有声望进度，完成特定交易可以提升声望，更高等级会解锁额外的兑换任务。',
    '第一次接触维克洛可以先完成他的介绍任务，别一进门就开始研究怎么把整个店搬空。',
    '维克洛人情本身就是一种兑换货币，先囤人情，看到以后想换的东西会方便很多。',
    '50 个雇佣兵凭证也可以通过对应兑换任务换 1 个维克洛人情。',
    '4.10 有些新的维克洛飞船兑换不是让你直接交一堆材料了，先看展厅牌子接任务。',
    '4.10 的新式飞船兑换会给你一次性蓝图，需要先用制造机把维克洛指定的物品制造出来。',
    '新式飞船兑换完成后可以选择现在提船或者以后再提，不一定非得当场开走。',
    '别人逛维克洛是购物，我逛维克洛是上班。',
    '别问我为什么知道每个兑换要什么。',
  ],
  exitTitle: 'ASRC_WWW',
  exitMessage: '行，你自己慢慢研究。',
  exitMark: '👀',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 40,
},

furysoulfy: {
  name: 'Furysoulfy · 焰联行政王',
  image: '/images/characters/furysoulfy.png',
  alt: 'Furysoulfy 焰联行政王',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: '焰联行政王の行政机库提示',
  messages: [
    '行政机库不是终点，是下一轮肝帝生活的起点。',
    '进争夺区之前先检查装备，进去以后可没人等你。',
    '进门以后记一下自己走过的路线，打到后面迷路有时候比遇到敌人还麻烦。',
    '来都来了，不开个行政机库再走？',
    '听到附近有枪声别急着往前冲，先判断是 NPC 还是其他玩家在交火。',
    '欢迎来到行政机库，接下来就看你的运气了。',
    '搜东西的时候留个人看周围，四个人一起低头翻箱子属于给别人准备团灭素材。',
    '拿到值钱的东西以后先想怎么安全带出去，捡到不等于已经是你的。',
    '队友倒地先报位置和敌人方向，救人之前最好先把附近威胁处理掉。',
    '准备长时间待在争夺区的话多带一点医疗和弹药，里面可没有便利店，除了死局争夺区。',
    '行政机库这种东西，飞到地方只是第一步，能不能坚持到五个绿灯把机库打开才算真的结束。',
    '争夺区行政机库需要帮忙喊我~',
    '进争夺区就跟回家了一样~',
  ],
  exitTitle: 'Furysoulfy',
  exitMessage: '行，我先去开下一间行政机库。',
  exitMark: '👋',
  exitMarkX: 42,
  exitMarkY: 9,
  exitMarkSize: 42,
},

furinlada: {
  name: 'Furinlada · 拉达',
  image: '/images/characters/furinlada.png',
  alt: 'Furinlada 拉达',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  autoCycle: true,
  cycleInterval: 5000,
  doubleClose: true,
  title: '酒馆鲁迅の活动观察',
  messages: [
    '有的人参加活动是为了赢，有的人参加活动，是为了给下一篇事故报告提供素材。',
    '英仙座：让我们重新战斗吧。众wbccu：好，很有精神。',
    '活动尚未开始，事故已经在路上了。',
    '世上本没有翻车，坐狮王船的人多了，也便有了翻车。',
    '有人问我为什么总站在旁边看。因为冲在前面的，通常已经躺下了。',
    '活动最大的魅力，大概就是计划永远赶不上群友的临场发挥。',
    '有的人活着，他已经迷路了；有的人死了，他还在语音里报点。',
    '真正的勇士，敢于直面服务器掉线，也敢于正视队友离谱的驾驶技术。',
    `下面聊点1万的，不是沙特的不要听。你，是一个土豪，你，有三艘小姨，一艘标枪，台下一片欢呼，哇，你好勇敢，你在公民玩战舰世界爬线还爬到顶了。接着你说✌️你要买两艘奥丁，天呐，下面人狂欢哪，你要买一万块的船`,
    `近日伟大的领导人、太阳，【REDACTED】探访了近日举办的2026年文昌鸡能飞国际航空航天博览会并荣获来自英国航天业的太空飞行器：惩戒号LTI与比例微缩模型一份。伟大的太阳为人类航空航天事业快速发展向参会的各国航空航天行业从业者与英国王室表达了诚挚的感激之情。不日，英国王室返还了相当的祝贺，并保证将督促英国皇家空军旗下罗伯茨航天工业主席克里斯罗伯茨尽快实现这一舰船的落实。目前，包括董事长克里斯罗伯茨及公司首席运营官维亚切斯拉夫·巴兰尼科夫，首席舰船构筑师安东·尤丁采夫和首席试飞员尼基塔·布亚诺夫暂未发表回应。`,
    `你的游戏好烂
     你的bug好多
     你的进度好慢
     你的内容好少
     你的活动好牢
     但是我喜欢`,
      `“突发，~~前~~42中队制作人名下游艇与他人发生撞船事故，救援队赶到时发现克里斯罗伯茨先生正在摆出军礼姿势缓慢沉没，但是救援队中的星际公民玩家不顾自身危险奋力将其营救成功。目前打捞到的残骸中发现刹船片上有遭到破坏的痕迹，并在疑似发动机的残骸上发现刻痕，文本为酒馆著名角色：“Lion_Shipcrasher 狮王”。同时另一艘船上的乘客仍旧失踪，名单为：“维亚切斯拉夫·巴兰尼科夫、安东·尤丁采夫、尼基塔·布亚诺夫”。请市民踊跃报告线索，无论生死。`,
      `只见萝卜在呢黄金王座上被狠狠电击，嘴里脱口欲出什么“sī…sī”
“他莫非参透了宇宙的终极奥秘？”
“不！肯定是那传说中存在又不存在，不可言说的U Know Who游戏？”
“说啊，快说啊，你到底想说什么！？”
萝卜终于无法压制那奔腾涌动的伟力，自下而上，他的全身细胞仿佛都在嘶吼出：
“SIX 7！”`,
  ],
  exitTitle: '拉达留下了一句话',
  exitMessage: '罢了，世间喧嚣，我去别处再看看。',
  exitMark: '…',
  exitMarkX: 45,
  exitMarkY: 8,
  exitMarkSize: 40,
},

reyindehlort: {
  name: 'ReyinDehlort · Reyin',
  image: '/images/characters/reyindehlort.png',
  alt: 'ReyinDehlort Reyin',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 320,
  bubbleTailOffset: 40,
  title: 'Reyinの摸鱼时间',
  messages: [
    '准备差不多就行了，剩下的进游戏再说。',
    '这个事情吧……明天再说。',
    '不是必须带的东西就别全塞背包里，轻装一点死了也没那么心疼。',
    '本来想认真一下，后来想想还是算了。',
    '能混过去为什么要那么努力？',
    '你们继续，我先撤了。',
    '出发前顺手确认一下复活点，出事以后能少坐一次漫长的电梯和地铁。',
    '多人行动掉队了先别自己乱飞，语音里问一下队伍在哪通常更快。',
    '任务地点离得远的话先看看量子燃料，飞到一半再找加油站就不摸鱼了。',
  ],
  exitTitle: 'Reyin',
  exitMessage: '走了，不搞了。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

walkertian: {
  name: 'Walkertian · 圈圈',
  image: '/images/characters/walkertian.png',
  alt: 'Walkertian 圈圈',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: '麦当劳店长の工具推荐',
  messages: [
    'Discord 里的 <t:时间戳> 会自动按每个人自己的时区显示，跨时区约活动很好用。',
    '延迟突然变高不一定是你家网络的问题，先看看服务器和其他玩家是不是也一样。',
    '游戏更新以后下载速度异常，可以先检查启动器的并发下载和带宽限制设置。',
    '遇到网络问题先分清楚是延迟高、丢包还是服务器卡顿，这三个看起来很像但不是一回事。',
    '飞船突然完全没反应，先看看是不是发动机、电源或者主电闸被关了，别急着直接退游戏。',
    '复制 Discord 动态时间之前记得确认 AM 和 PM，差十二个小时可不是小误差。',
    '飞船门打不开的时候先看看是不是锁船了，自己的船把自己关在外面也不是没发生过。',
    '量子跳跃用不了的时候，先确认有没有设置目的地、有没有离开阻碍区域，再看看量子驱动器状态。',
    '机库门一直不开，可以先确认有没有通过 ATC 申请起飞，很多时候不是门坏了。',
    '任务标记突然消失，先打开 mobiGlas 看一下任务是不是还在追踪，服务器卡顿也可能让标记暂时不显示。',
    '电梯按钮没反应先等几秒再按，连续狂点通常不能让星际公民的服务器思考得更快。',
    '突然不能喝水吃东西，先确认头盔摘了没有。这个问题每个公民迟早都会问一次。',
    '武器或者装备拖不动时先等一下库存同步，连续拖几十次有时候只会让情况更乱。',
    '买完装备找不到，先确认购买时选择的是哪个地点库存，它不一定直接出现在你身上。',
    '准备离开空间站前顺手检查医疗、弹药和补给，飞到任务地点才发现少东西最浪费时间。',
    '服务器明显开始抽风的时候，先别急着做高价值交易或者搬全部家当，等稳定一点通常更保险。',
    '遇到 Bug 如果重进游戏也没解决，可以先问问酒馆里其他人是不是也遇到了，很多时候你不是唯一一个。',
  ],
  exitTitle: '麦当劳店长',
  exitMessage: '先不聊了，店里又来事了。',
  exitMark: '🍟',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

cyanaemorrachi: {
  name: 'CyanaEmorrachi · CY',
  image: '/images/characters/cyanaemorrachi.png',
  alt: 'CyanaEmorrachi CY',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 330,
  bubbleTailOffset: 40,
  title: 'CYの活动提示',
  messages: [
    '平时叫我上线不一定来，集体活动可以喊我。',
    '参加群飞前最好确认一下活动需要什么船，别所有人到了才发现舰种完全对不上。',
    '群飞记得喊我，正好把买了没怎么开的船拉出来。',
    '大型舰船集合的时候尽量提前把船开出来，现场几十个人一起出库很容易堵机库。',
    '合影用船不一定越大越好，统一舰种和队形有时候比堆一排大船更好看。',
    '开什么船参加？算了，我直接再买一艘。',
    '这活动不错，终于有理由把机库里的船开出来了。',
    '合影站哪都行，船一定得停在显眼的位置。',
    '你们先集合，我还在机库里纠结开什么船。',
    '多人舰船活动最好提前分一下驾驶、炮手和其他岗位，上船以后再抢位置会比较乱。',
    '群飞的时候别只顾着看自己的船，保持间距比队形贴得特别近更重要。',
  ],
  exitTitle: 'CY',
  exitMessage: '你们先拍，我再去机库看看船。',
  exitMark: '🚀',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

walkerjack4396: {
  name: 'Walkerjack4396 · Jack',
  image: '/images/characters/walkerjack4396.png',
  alt: 'Walkerjack4396 Jack',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: 'Jackの游戏提示',
  messages: [
    '进 PTU 前最好先看一下当前测试说明，有些功能没开放不一定是 Bug。',
    '新版本刚更新以后遇到问题，可以先看看是不是服务器普遍现象，别急着重装游戏。',
    '新版本？PTU开了我可以先进去看看。',
    '测试服更新比较频繁，上线前最好先看一眼有没有新补丁，省得准备半天又要更新。',
    '活动要帮忙是吧？行，到时候叫我。',
    '游戏就和人生一样，都佛系一点。',
    '遇到能稳定复现的 Bug，记一下步骤再去 Issue Council 报告，比单纯说“游戏坏了”有用得多。',
    '要去PTU测试新东西可以找我。',
    'PTU 的进度和物品本来就可能重置，测试服里还是别太在意家底。',
    '新版本第一天服务器不稳定很正常，重要活动最好别把所有准备都押在刚开服的时候。',
  ],
  exitTitle: 'Jack',
  exitMessage: '不是，那你们先搞，我先撤了。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

sleepmita: {
  name: 'Sleepmita · 米塔',
  image: '/images/characters/sleepmita.png',
  alt: 'Sleepmita 米塔',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 330,
  bubbleTailOffset: 40,
  title: '米塔の活动疑问',
  messages: [
    '啊？今天有合影活动？在哪里集合？等等我，我现在飞过来。',
    '完啦，我忘记绑复活点了，死回主城了...',
    '完啦，下船之前忘记戴头盔啦，要憋死了。',
    '啊？今天是干嘛来着？完啦，有活动啊。',
    '啊？活动有这个要求吗，我没看活动公告啊。',
    '啊？进电梯之前还要看它到底有没有真的到？我已经掉进虚空了...',
    '啊？我没穿宇航服……这里外面不能呼吸的吗？',
    '啊？任务地点在另一颗星球？我还以为就在旁边。',
    '啊？等一下，我还没绑复活点，已经死透了...',
    '啊？Discord 这个活动时间会自动显示成我自己的时区？',
  ],
  exitTitle: '米塔',
  exitMessage: '啊？你怎么关掉了？',
  exitMark: '？',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 48,
},

embergt: {
  name: 'EmberGT · Ember',
  image: '/images/characters/embergt.png',
  alt: 'EmberGT Ember',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 330,
  bubbleTailOffset: 40,
  title: 'Emberの活动提醒',
  messages: [
    '活动开始前可以提前几分钟上线，检查一下装备、补给和复活点，后面会轻松很多。',
    '大型活动人多的时候尽量听指挥统一行动，大家各走各的反而会花更多时间。',
    '准备登船之前可以先确认一下还有没有队友在路上，等等大家也没关系。',
    '出发前可以顺手检查一下医疗枪和治疗针，真正需要的时候再发现没带就晚了。',
    '多人活动最好一直待在队伍语音里，临时改变集合点的时候不容易掉队。',
    '长时间行动记得带一点水和食物，有些活动比预计时间长很多。',
    '装备准备好了和复活点也绑定好了，随时可以开始。',
    '如果队友倒地了先确认周围安全，再过去救人，不然很容易一起躺下。',
    '任务结束以后别急着直接退游戏，重要装备和战利品最好先存回仓库。',
    '有什么需要我帮忙的吗？',
  ],
  exitTitle: 'Ember',
  exitMessage: '好，那我先走啦，下次活动见。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

'500ping': {
  name: '500ping',
  image: '/images/characters/500ping.png',
  alt: '500ping',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: '500pingの活动意见',
  messages: [
    '参加之前还是先看一遍活动公告吧，虽然有时候真的写得好多。',
    '等等，我应该没迟到太久吧？',
    '活动我肯定来，就是可能稍微晚那么一点点。',
    '集合地点和时间最好先确认一下，不然跑错地方更麻烦。',
    '规则看起来麻烦归麻烦，比赛的时候还是得按规则来。',
    '等一下，我是不是漏看了什么？',
    '比赛类活动记得提前确认赛制和胜负条件，打完才发现理解错规则就尴尬了。',
    '发现活动流程哪里不合理可以直接提，规则本来就是可以慢慢优化的。',
    '集合前先确认时间和地点，尤其注意 Discord 动态时间显示的是你自己的本地时间。',
    '活动要求共享屏幕的话最好提前测试一下，开赛以后再调设置容易耽误双方时间。',
  ],
  exitTitle: '500ping',
  exitMessage: '好吧，那我回头再提建议。',
  exitMark: '💬',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

lightrepulsor: {
  name: 'LightRepulsor',
  image: '/images/characters/lightrepulsor.png',
  alt: 'LightRepulsor',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 112,
  bubbleWidth: 330,
  bubbleTailOffset: 40,
  title: 'LightRepulsorの活动时间',
  messages: [
    '天灾电磁炮发射！',
    '大型活动人多的时候尽量跟着队伍走，自己跑丢了再找大部队可就有意思了。',
    '准备合影的时候先别乱跑，几十个人重新站一次位置真的会很久。',
    '合影前最好把武器收起来，不然一个手滑可能直接变成大型事故现场。',
    '多人集合尽量别把飞船停在必经的位置，尤其是机库门口和起降区。',
    '组队以后记得确认队友都进了同一个服务器，不然语音里聊半天可能根本不在一个宇宙。',
    '活动途中如果掉线了先在语音里说一声，队伍至少知道不是你突然跑路了。',
    '大型合影想截图的话可以先把 HUD 关掉，画面会干净很多。',
    '集体行动的时候别随便开枪试武器，星际公民最不缺的就是意外。',
    '集体合影的时候飞船别乱开，别成为第二个狮王。',
  ],
  exitTitle: 'LightRepulsor',
  exitMessage: '哈哈，行，那我先溜了，下次活动见。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

coolapplepie: {
  name: 'coolapple-pie · 空战英豪',
  image: '/images/characters/coolapple-pie.png',
  alt: 'coolapple-pie 空战英豪',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 88,
  bubbleOffsetY: 90,
  bubbleWidth: 330,
  bubbleTailOffset: 14,
  title: '空战英豪の狗斗技巧',
  messages: [
    '狗斗速度要管理好，在合适的时机进出速度墙才能在需要的时候卡对方位置。',
    '远距离别只盯着预瞄点，看他机体移动趋势预判出自己的预瞄点。',
    '滚转不是越快越好，真正重要的是让自己的滚转转对的同时反应时间快。',
    '跟丢目标以后别急着乱转，优先下推拉开距离重新建立视野。',
    '伤害能打一点是一点，但是弹匣空了一定要等回弹。',
    '被对方抓到位置后优先拉开距离，贴的越近你开火的窗口就越少。',
    '狗斗里速度不是只有满速和零，学会根据位置和距离不断调整速度往往不会丢位置。',
    '距离拉得太近不一定是优势，贴得太死反而可能让自己没有足够空间调整机头。',
    '打不过的时候可以先录下自己的狗斗录像，复盘自己在哪一次转向之后丢掉了位置。',
    '真正稳定的狗斗不是靠一次神操作，而是连续很多次都比对面少犯一个错误。',
  ],
  exitTitle: 'coolapple-pie',
  exitMessage: '继续练，下次空战英豪赛场上见。',
  exitMark: '✈',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

shanora: {
  name: 'shanora · 山河',
  image: '/images/characters/shanora.png',
  alt: 'shanora 山河 星际摄影师',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: '星际摄影师の摄影技巧',
  messages: [
    '截图之前先把 HUD 关掉，少掉那些界面元素以后，画面通常立刻就干净很多。',
    '别急着按快门，先看看飞船、人物和背景之间有没有明显的重叠。',
    '拍飞船不一定要把整艘船塞进画面，适当裁掉一部分有时候反而更有压迫感。',
    '遇到漂亮的光线可以多换几个角度，同一个地点顺光、侧光和逆光完全是三张照片。',
    '画面太平的时候试试把主体放到画面三分之一附近，不一定每次都要正中构图。',
    '拍舰队合影的时候先统一队形和间距，后期调色救不了一开始就乱掉的阵型。',
    '太空里背景很黑，可以找行星、空间站或者星云做背景，让主体轮廓更容易被看清。',
    '截图的时候多留一点画面边缘，后期裁图永远比发现主体被切掉更容易处理。',
    '想让飞船看起来更有速度感，可以尝试降低视角，让背景和飞行方向参与构图。',
    '好截图不一定来自最稀有的地点，光线、构图和抓到的瞬间往往比地点本身更重要。',
  ],
  exitTitle: '山河',
  exitMessage: '先拍到这里，下次影廊见。',
  exitMark: '📷',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

meteorowo: {
  name: 'Meteor_OwO · 拾荒佬',
  image: '/images/characters/meteor-owo.png',
  alt: 'Meteor_OwO 拾荒佬',
  side: 'left',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: '拾荒佬の拾荒提示',
  messages: [
    '如果活着不能捡垃圾，那跟死了有什么区别。',
    '没人就放心大胆地吃，有人就提心吊胆地吃。',
    '捡垃圾的秘诀：吃完小退比开船回去存更安全。',
    '穿着基底服去捡垃圾，能比别人多带一套装备。',
    '当你的背包装不下的时候，别忘了你还有一双手。',
    '当你的包里有好东西时，遇到的人都是你的敌人。',
    '游戏里的奖励虽好，但陪你一起玩的朋友才是你最珍贵的宝物。',
    '高价值装备先拿，普通东西有空间再说。拾荒不是搬家公司。',
    '在捡垃圾时，当地的NPC能不清就不清，他们是最忠实的哨兵。',
    '穿的越穷，库存越富，穿的越富，钱包越富。',
  ],
  exitTitle: 'Meteor_OwO',
  exitMessage: '行，我去别的残骸看看还有没有好东西。',
  exitMark: '📦',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

arx93: {
  name: 'ARX-93 · 打捞专家',
  image: '/images/characters/arx-93.png',
  alt: 'ARX-93 打捞专家',
  side: 'right',
  height: 430,
  offsetX: 24,
  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,
  title: '打捞专家の打捞技巧',
  messages: [
    '秃鹫永远是你最好的伙伴，而不是回收者。',
    '打捞不是光盯着船体一直扫，移动路线规划好一点，能少做很多来回调整。',
    '打捞永远是与时间赛跑，因此在船皮价格不如建筑材料但却不用等待精炼的情况下，请不要将打捞罐中的为精炼建筑材料取出，并前往精炼站将其直接出售。',
    '打捞目标的货舱是个好地方，请务必先对其进行检查。',
    '船皮在UEX上的简称是RMC，而建筑材料是CMAT。',
    '不要用牵引模块替代打捞头，那并不会为打捞过程带来丝毫帮助。',
    '粉碎力场可以无视舰船护盾。',
    '打捞的时候要注意周遭环境。',
    '准备返航前检查一下货舱和飞船状态，别辛苦打捞半天最后把收益留在半路。',
    '别人看到残骸会绕开，我看到残骸只想问一句：还能刮多少？',
  ],
  exitTitle: 'ARX-93',
  exitMessage: '先打捞到这里，货舱满了，该回去卖货了。',
  exitMark: '🔧',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

combostar: {
  name: 'Combostar · 奥里森拳皇',
  image: '/images/characters/combostar.png',
  alt: 'Combostar 奥里森拳皇',

  side: 'right',
  height: 500,
  offsetX: 24,

  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,

  title: '奥里森拳皇の拳法秘诀',

  messages: [
    '一上来就抡重拳，多半先累的是你。',
    '觉得能多打一拳的时候，通常已经该停了。',
    '别想着每一下都打重，稳定命中比单次伤害重要。',
    '一直进攻没问题，前提是你知道什么时候该撤。',
    '自己体力见底之前先拉开，不要等完全没劲了再跑。',
    '不是谁出拳多谁赢，是谁的有效拳更多。',
    '对方防得严，就先把他体力磨掉，再找空档。',
    '别陪对面拼谁更能扛，逼他先把体力花完。',
  ],

  exitTitle: 'Combostar',
  exitMessage: '拳练完了再来找我。',

  exitMark: '🥊',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,

  autoCycle: true,
  cycleInterval: 9000,
  doubleClose: false,
},

ttv550: {
  name: 'TTV550 · 黄金矿工',
  image: '/images/characters/ttv550.png',
  alt: 'TTV550 黄金矿工',

  side: 'left',
  height: 430,
  offsetX: 24,

  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,

  title: '黄金矿工の采矿提示',

  messages: [
    '绝世好服是第一生产力。',
    '自己找矿挖矿并不一定是获取高品矿物的唯一途径。或许你花十个小时赚到的游戏币，能够在玩家市场上买到你花二十个小时也不见得能找到的高品矿物。。',
    '谨慎考虑你挖矿的最终目的。用花了数十上百小时挖出的高品矿物制造出的超高品质道具，很可能在一次版本平衡性调整中被一脚踢入下水道。',
    '能开采更大矿石的矿船就是更好的矿船。在猎户座和阿拉斯塔实装可飞之前，鼹鼠就是最好的矿船。',
    '对于一个矿工来说，最好的挖矿组件是另一个矿工，其次才是那些大功率、大绿区的采矿激光头。',
    '鼹鼠的改装？我认为通用性最强的方案是：螺旋II加三个里格III，霍夫斯塔德II加两个聚焦III，刀轴II加两个聚焦III。',
    '充分的准备工作是成功挖矿的开始。建议出发前在自己的背包里或矿船库存里带足吃喝、消耗型模组以及合适的采矿贴片。',
    '寻找高品矿物的过程是漫长而艰辛的，因此一定要调整心态。记住：找不到才是常态，找到了是意外。',
    '今天不找到高品质矿不下机。',
  ],

  exitTitle: 'TTV550',
  exitMessage: '矿还没挖完，我先回去继续干活了。',
  exitMark: '⛏️',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

vt7prototype: {
  name: 'VT7Prototype',
  image: '/images/characters/vt7prototype.png',
  alt: 'VT7Prototype',

  side: 'left',
  height: 430,
  offsetX: 24,

  bubbleOffsetX: 38,
  bubbleOffsetY: 105,
  bubbleWidth: 340,
  bubbleTailOffset: 40,

  title: 'VT7Prototypeの活动提示',

  messages: [
    '参加大型活动之前先看一遍公告，集合地点和时间搞错一个都能让你跑半个星系。',
    '活动开始前提前上线检查装备，比集合以后才发现东西没带轻松多了。',
    '多人行动的时候尽量跟着队伍走，一个人跑太快最后通常还是得回来找大部队。',
    '活动需要特定装备的话最好提前准备，现场几十个人一起找装备会拖很久。',
    '复活点能提前绑就提前绑，真正出事以后你会感谢之前的自己。',
    '大型活动掉线了先在语音里说一声，至少大家知道你不是突然失踪了。',
    '准备合影的时候先别乱动，几十个人重新排一次队真的很久。',
    '需要帮忙直接喊，活动人多的时候最不缺的就是人手。',
    '活动流程可能会临时调整，待在语音里会比一直问“现在去哪”方便很多。',
    '人齐了？那就出发。',
  ],

  exitTitle: 'VT7Prototype',
  exitMessage: '行，我先撤了，下次活动再见。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

raineyday: {
  name: 'Raineyday · 焰联行政王',
  image: '/images/characters/raineyday.png',
  alt: 'Raineyday 焰联行政王',

  side: 'right',
  height: 430,
  offsetX: 24,

  bubbleOffsetX: 58,
  bubbleOffsetY: 90,
  bubbleWidth: 340,
  bubbleTailOffset: 40,

  title: '焰联行政王の行政机库提示',

  messages: [
    '行政机库绿灯亮了以后别急着走，先确认这一轮流程真的完成了。',
    '进争夺区之前把医疗、弹药和装备准备好，里面可不是进去以后再慢慢整理背包的地方。',
    '行政机库最需要的不是着急，是把每一步都稳定做完。',
    '进争夺区以后记一下路线，打着打着找不到出口比遇到敌人还麻烦。',
    '听到枪声先判断方向，别一听见动静就带着整队人往枪口上跑。',
    '高价值东西拿到手以后第一件事不是继续搜，是先想怎么安全带出去。',
    '开行政机库之前把人员和装备确认好，临时缺一个人往往比缺一把枪更麻烦。',
    '绿灯还没齐？那就继续。',
    '争夺区这种地方，活着把东西带出来才算真正拿到了。',
    '又要开行政机库？走。',
  ],

  exitTitle: 'Raineyday',
  exitMessage: '我先去看看下一轮行政机库。',
  exitMark: '👋',
  exitMarkX: 43,
  exitMarkY: 8,
  exitMarkSize: 42,
},

} satisfies Record<string, PageCompanionConfig>

export type PageCompanionId = keyof typeof PAGE_COMPANIONS